// src/components/Carousel.tsx
import { Card, CardContent } from "@/components/ui/card"
import {
  Carousel,
  CarouselContent,
  CarouselItem,
  CarouselNext,
  CarouselPrevious,
  type CarouselApi,
} from "@/components/ui/carousel"
import Autoplay from 'embla-carousel-autoplay'
import { WheelGesturesPlugin } from 'embla-carousel-wheel-gestures'
import * as React from "react"


export default function MediaCarousel({ items, showSlideNumbers = true }: { items: string[], showSlideNumbers?: boolean}) {
  const plugin = React.useRef(
    Autoplay({ delay: 3000, stopOnInteraction: true })
  )

  const [api, setApi] = React.useState<CarouselApi>()
  const [current, setCurrent] = React.useState(0)
  const [count, setCount] = React.useState(0)
 
  React.useEffect(() => {
    if (!api) {
      return
    }
 
    setCount(api.scrollSnapList().length)
    setCurrent(api.selectedScrollSnap() + 1)
 
    api.on("select", () => {
      setCurrent(api.selectedScrollSnap() + 1)
    })
  }, [api])

  const getMediaType = (item: string) => {
    const extension = item.split('.').pop()?.toLowerCase();
    switch (extension) {
      case 'mp4':
      case 'webm':
      case 'mov':
      case 'ogg':
        return 'video';
      case 'jpg':
      case 'jpeg':
      case 'png':
      case 'gif':
      case 'webp':
        return 'image';
      default:
        return 'unknown';
    }
  }

  return (
    <Carousel
    setApi={setApi}
    className="mx-auto p-0"
    opts={{loop: true}}
    plugins={[plugin.current, WheelGesturesPlugin({forceWheelAxis: "y"})]}
    onMouseEnter={plugin.current.stop}
    onMouseLeave={() => { plugin.current.play(); plugin.current.reset(); }}>
      <CarouselContent className="p-0 h-[30rem]">
        {items.map((item, index) => (
          <CarouselItem key={index}>
            <Card className="flex h-full items-center p-0 !bg-neutral-950 justify-center">
              <CardContent className="p-4 flex justify-center rounded-lg items-center">
                {(() => {
                  switch (getMediaType(item)) {
                    case 'image':
                      return <img src={item} alt="media" className="pointer-events-none max-h-96 !w-auto mx-auto" />;
                    case 'video':
                      return (
                        <video className="pointer-events-none max-h-96 !w-auto mx-auto" autoPlay={true} muted={true} loop={true}>
                          <source src={item} type={`video/${item.split('.').pop()}`}/>
                        </video>
                      );
                    default:
                      return <p>Unsupported media type</p>;
                  }
                })()}
              </CardContent>
            </Card>
          </CarouselItem>
        ))}
      </CarouselContent>
      <CarouselPrevious />
      <CarouselNext />
      {showSlideNumbers && (
        <div className="py-2 text-center text-sm text-neutral-600 hover:text-neutral-400 transition-colors duration-300">
          Slide {current} of {count}
        </div>
      )}
    </Carousel>
  )
}

// src/lib/components/svelte/Carousel.svelte
<script lang="ts">
  import * as Card from "$lib/components/ui/card/index.ts";
  import { type CarouselAPI } from "$lib/components/ui/carousel/context.ts";
  import * as Carousel from "$lib/components/ui/carousel/index.ts";
  import { getMediaType } from "$lib/utilities";
  import Autoplay from "embla-carousel-autoplay";
  import { WheelGesturesPlugin } from "embla-carousel-wheel-gestures";

  const { items = [], showSlideNumbers = true }: { items: string[]; showSlideNumbers: boolean } = $props();

  const plugin = Autoplay({ delay: 3000, stopOnInteraction: true });

  let api = $state<CarouselAPI>();
  let current = $state(0);

  const count = $derived(api ? api.scrollSnapList().length : 0);

  $effect(() => {
    if (api) {
      current = api.selectedScrollSnap() + 1;
      api.on("select", () => {
        current = api!.selectedScrollSnap() + 1;
      });
    }
  });
</script>

<Carousel.Root
  setApi={(emblaApi) => (api = emblaApi)}
  class="mx-auto p-0"
  opts={{ loop: true }}
  plugins={[plugin, WheelGesturesPlugin({ forceWheelAxis: "y" })]}
  onmouseenter={plugin.stop}
  onmouseleave={() => {
    plugin.play();
    plugin.reset();
  }}>
  <Carousel.Content class="h-[30rem] p-0">
    {#each items as item}
      <Carousel.Item>
        <Card.Root class="border-border bg-popover flex h-full items-center justify-center p-0">
          <Card.Content class="flex items-center justify-center rounded-lg p-4">
            {#if getMediaType(item) === "image"}
              <img src={item} alt="media" class="pointer-events-none mx-auto max-h-96 w-auto!" />
            {:else if getMediaType(item) === "video"}
              <video class="pointer-events-none mx-auto max-h-96 w-auto!" autoPlay={true} muted={true} loop={true}>
                <source src={item} type={`video/${item.split(".").pop()}`} />
              </video>
            {:else}
              <p>Unsupported media type</p>
            {/if}
          </Card.Content>
        </Card.Root>
      </Carousel.Item>
    {/each}
  </Carousel.Content>
  <Carousel.Previous />
  <Carousel.Next />
  {#if showSlideNumbers}
    <div class="py-2 text-center text-sm text-neutral-600 transition-colors duration-300 hover:text-neutral-400">
      Slide {current} of {count}
    </div>
  {/if}
</Carousel.Root>
